export { default as backgroundObject } from './backgroundObject'
export { default as blockObject } from './blockObject'
export { default as playerObject } from './playerObject'
export { default as otherPlayerObject } from './otherPlayerObject'
export { default as portalObject } from './portalObject'
export { default as bouncingBallObject } from './bouncingBallObject'
export { default as playerManagerObject } from './playerManager'